In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('dados_hdi.xlsx')
#df.head()

In [3]:
df.set_index('Country',inplace=True)
#df.head()
#df.drop('Index', axis=1)
#df.describe()
#df.info()

In [4]:
cols = df.columns.drop(['Index'])
cols
df[cols] = df[cols].apply(pd.to_numeric, errors = 'coerce')
#df.info()

In [5]:
continent = pd.read_excel('continent.xlsx')
#continent.head()
continent.set_index('Country',inplace=True)
continent.head()

                               Continent
Country
Algeria                           Africa
Angola                            Africa
Benin                             Africa
Botswana                          Africa
British Indian Ocean Territory    Africa

In [6]:
######Dealing with missing Continent Values!
empty = df.columns[df.isna().any()].tolist()
df_cols = df[empty]
df_cols = df_cols.join(continent, on='Country', how='left', lsuffix='Country', rsuffix='Country')

cont = df_cols[['Continent']] 
empty_cont = cont[cont['Continent'].isnull()]
empty_cont

                                   Continent
Country
Hong Kong, China (SAR)                   NaN
United Kingdom                           NaN
United States                            NaN
Korea (Republic of)                      NaN
Moldova (Republic of)                    NaN
Palestine, State of                      NaN
Eswatini (Kingdom of)                    NaN
Côte d'Ivoire                            NaN
Tanzania (United Republic of)            NaN
Congo (Democratic Republic of the)       NaN

In [7]:
###Filling empty Continents!!!
cont_dict = {'Hong Kong, China (SAR)': 'Asia','United Kingdom' : 'Europe','United States':'North America',
             'Korea (Republic of)':'Asia','Moldova (Republic of)':'Europe','Palestine, State of':'Asia',
             'Eswatini (Kingdom of)':'Africa', "Côte d'Ivoire":'Africa',
             'Tanzania (United Republic of)':'Africa','Congo (Democratic Republic of the)':'Africa'}

cont_dict = pd.DataFrame(list(cont_dict.items()),columns = ['Country','Continent'])
cont_dict.set_index('Country',inplace=True)
cont_dict

                                        Continent
Country
Hong Kong, China (SAR)                       Asia
United Kingdom                             Europe
United States                       North America
Korea (Republic of)                          Asia
Moldova (Republic of)                      Europe
Palestine, State of                          Asia
Eswatini (Kingdom of)                      Africa
Côte d'Ivoire                              Africa
Tanzania (United Republic of)              Africa
Congo (Democratic Republic of the)         Africa

In [8]:
cont = cont.fillna(cont_dict)
#cont.head()

In [9]:
df = df.join(cont, on='Country', how='left', lsuffix='Country', rsuffix='Country')
df.head()

,Index,Ranking_HDI_2019,Human Development Index (HDI) Value (2019),"Life expectancy at birth (years, 2019)","Expected years of schooling (years, 2019)","Mean years of schooling (years, 2019)",Gross national income (GNI) per capita 2019 (2017 PPP $),Gender Development Index - Value (2019),Gender Inequality Index Value (2019),Inequality-adjusted HDI (IHDI) Value 2019,...,"Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)","Carbon dioxide emissions: Production emissions per capita (tonnes, 2018)",Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP),"Forest area (% of total land area, 2016)",Forest area - Change 1990/2016 (%),Domestic material consumption per capita (tonnes. 2017),"Red List Index (value, 2019)","Skilled labour force (% of labour force, 2010-2019)","Research and development expenditure (% of GDP, 2014-2018)",Continent
Country,,,,,,,,,,,,,,,,,,,,,
Norway,1,1,0.957,82.40,18.06615,12.897750,66494.25217,0.989939,0.045,0.899,...,100.000000,8.303974,0.10907,33.17786,-0.115284,21.82197,0.93923,84.2811,2.06985,Europe
Ireland,2,2,0.955,82.31,18.70529,12.666331,68370.58737,0.981024,0.093,0.885,...,95.307037,8.079187,0.11213,11.02773,63.376347,13.47527,0.91522,85.0470,1.14647,Europe
Switzerland,3,2,0.955,83.78,16.32844,13.380812,69393.52076,0.967513,0.025,0.889,...,98.856651,4.325016,0.07975,31.83015,9.314837,13.71868,0.97459,87.3141,3.37286,Europe
"Hong Kong, China (SAR)",4,4,0.949,84.86,16.92947,12.279960,62984.76553,0.972323,NaN,0.824,...,94.702423,5.852683,0.10847,NaN,NaN,NaN,0.83060,76.9800,0.86096,Asia
Iceland,5,4,0.949,82.99,19.08309,12.772787,54682.38057,0.968674,0.058,0.894,...,NaN,10.782476,0.13471,0.50374,213.664589,14.88115,0.86310,76.1659,2.02994,Europe

In [10]:
#Verifing the columns with empty values!!!
empty = df.columns[df.isna().any()].tolist()
df_cols = df[empty]
df_cols

,Gender Development Index - Value (2019),Gender Inequality Index Value (2019),Inequality-adjusted HDI (IHDI) Value 2019,"Inequality in life expectancy (%, 2015-2020)","Inequality in education (%, 2019)","Inequality in income (%, 2019)",Gender Inequality Index Value (2019).1,"Share of seats in parliament (% held by women, 2019)","Median age (years, 2020)",Current health expenditure (% of GDP),...,Physicians per 10000 people (2010-2018),"Hospital beds (per 10,000 people, 2010-2019)","Vulnerable employment (% of total employment, 2019)\n","Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)",Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP),"Forest area (% of total land area, 2016)",Forest area - Change 1990/2016 (%),Domestic material consumption per capita (tonnes. 2017),"Skilled labour force (% of labour force, 2010-2019)","Research and development expenditure (% of GDP, 2014-2018)"
Country,,,,,,,,,,,,,,,,,,,,,
Norway,0.989939,0.045,0.899,3.0,2.33240,12.56175,0.045,40.828402,39.836,10.446342,...,29.164,35.3,4.906,100.000000,0.10907,33.17786,-0.115284,21.82197,84.2811,2.06985
Ireland,0.981024,0.093,0.885,3.4,3.28604,14.97823,0.093,24.311927,38.246,7.184383,...,33.125,29.7,10.610,95.307037,0.11213,11.02773,63.376347,13.47527,85.0470,1.14647
Switzerland,0.967513,0.025,0.889,3.5,1.82879,14.93378,0.025,38.617886,43.053,12.346322,...,42.957,46.3,8.941,98.856651,0.07975,31.83015,9.314837,13.71868,87.3141,3.37286
"Hong Kong, China (SAR)",0.972323,NaN,0.824,2.5,9.80000,25.60000,NaN,NaN,44.790,NaN,...,NaN,NaN,5.717,94.702423,0.10847,NaN,NaN,NaN,76.9800,0.86096
Iceland,0.968674,0.058,0.894,2.4,2.79474,11.73652,0.058,38.095238,37.491,8.326291,...,40.778,28.3,8.108,NaN,0.13471,0.50374,213.664589,14.88115,76.1659,2.02994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Burundi,0.999288,0.504,0.303,28.5,39.50000,20.90000,0.504,38.750000,17.320,7.517570,...,1.001,7.9,94.581,6.726228,NaN,10.92679,-2.906572,1.75160,2.5288,0.21028
South Sudan,0.841802,NaN,0.276,36.2,39.60000,32.30000,NaN,26.558891,19.040,9.760994,...,NaN,NaN,84.854,4.708466,0.40508,NaN,NaN,0.90149,NaN,NaN
Chad,0.764091,0.710,0.248,40.9,43.00000,28.40000,0.710,14.880952,16.554,4.487301,...,0.434,NaN,93.024,14.850259,NaN,3.77097,-29.181210,2.52412,7.5754,0.30050
Central African Republic,0.801420,0.680,0.232,40.1,34.50000,49.20000,0.680,8.571429,17.611,5.821776,...,0.721,10.0,91.379,9.717617,NaN,35.56198,-1.797871,3.38292,NaN,NaN
Niger,0.723746,0.642,0.284,30.9,35.00000,16.40000,0.642,16.959064,15.151,7.739963,...,0.433,3.9,93.676,10.910047,0.10514,0.89177,-41.922880,3.41545,4.0424,NaN

In [11]:
##Calculating the means for each Continent!
df_cols_mean = df.groupby(['Continent']).mean()
df_cols_mean

,Index,Ranking_HDI_2019,Human Development Index (HDI) Value (2019),"Life expectancy at birth (years, 2019)","Expected years of schooling (years, 2019)","Mean years of schooling (years, 2019)",Gross national income (GNI) per capita 2019 (2017 PPP $),Gender Development Index - Value (2019),Gender Inequality Index Value (2019),Inequality-adjusted HDI (IHDI) Value 2019,...,"Rural population with access to electricity (%, 2018)","Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)","Carbon dioxide emissions: Production emissions per capita (tonnes, 2018)",Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP),"Forest area (% of total land area, 2016)",Forest area - Change 1990/2016 (%),Domestic material consumption per capita (tonnes. 2017),"Red List Index (value, 2019)","Skilled labour force (% of labour force, 2010-2019)","Research and development expenditure (% of GDP, 2014-2018)"
Continent,,,,,,,,,,,,,,,,,,,,,
Africa,151.773585,151.622642,0.560736,64.240755,10.724123,5.591836,5609.589052,0.896937,0.531674,0.389478,...,36.564247,33.304673,1.234537,0.178915,28.422215,-7.043666,5.895299,0.872425,27.622081,0.363091
Asia,90.187500,89.937500,0.742437,74.474792,13.237173,8.882099,22541.333653,0.917750,0.342477,0.620278,...,94.524573,53.024505,6.727974,0.291960,22.253228,8.089886,14.219249,0.836856,52.396528,0.793867
Europe,33.658537,33.365854,0.879707,79.414146,16.171684,11.914609,41255.893870,0.984438,0.116359,0.803333,...,100.000000,84.166024,6.574179,0.226727,34.029426,15.320599,15.197032,0.928915,84.277023,1.461787
North America,85.608696,85.304348,0.755957,75.488261,13.517982,9.227406,18521.216191,0.977550,0.363167,0.595267,...,93.356415,53.506631,4.941727,0.205860,38.573199,-2.001687,8.291296,0.775561,47.011620,0.560524
Oceania,101.166667,101.083333,0.714083,72.471667,13.837356,9.585902,13068.632991,0.963424,0.338167,0.658000,...,87.119760,99.267937,4.053550,0.264515,53.035459,3.849880,10.503613,0.741322,56.717800,1.090333
South America,84.916667,84.833333,0.763167,75.090833,14.557230,9.259490,13994.396607,0.978882,0.393167,0.611750,...,95.977090,53.963080,2.782684,0.191200,48.930135,3.788632,17.875299,0.834694,51.228125,0.409354

In [12]:
############ FILLING THE MISSING VALUES ######
###Finding them!!!
df_full = df

#### Dropping 2 collumns, Index and other that was duplicate!!!####
df_full = df_full.drop(['Gender Inequality Index Value (2019).1', 'Index'], axis=1)

#df.head()
df_full.isnull().sum()

Ranking_HDI_2019                                                                                                                       0
Human Development Index (HDI) Value (2019)                                                                                             0
Life expectancy at birth (years, 2019)                                                                                                 0
Expected years of schooling (years, 2019)                                                                                              0
Mean years of schooling (years, 2019)                                                                                                  0
Gross national income (GNI) per capita 2019 (2017 PPP $)                                                                               0
Gender Development Index - Value (2019)                                                                                               22
Gender Inequality Index Value (2019)                                                                                                  27
Inequality-adjusted HDI (IHDI) Value 2019                                                                                             37
Inequality in life expectancy (%, 2015-2020)                                                                                           6
Inequality in education (%, 2019)                                                                                                     18
Inequality in income (%, 2019)                                                                                                        33
Share of seats in parliament (% held by women, 2019)                                                                                   2
Total Population (millions, 2019)                                                                                                      0
Total Urban Population (%, 2019)                                                                                                       0
Median age (years, 2020)                                                                                                               6
Current health expenditure (% of GDP)                                                                                                  7
Government expenditure on education  (% of GDP, 2013-2018)                                                                            42
Physicians per 10000 people (2010-2018)                                                                                                5
Hospital beds (per 10,000 people, 2010-2019)                                                                                          24
Vulnerable employment (% of total employment, 2019)\n                                                                                 11
Rural population with access to electricity (%, 2018)                                                                                  0
Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)    34
Carbon dioxide emissions: Production emissions per capita (tonnes, 2018)                                                               0
Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)                                                                    51
Forest area (% of total land area, 2016)                                                                                               3
Forest area - Change 1990/2016 (%)                                                                                                     9
Domestic material consumption per capita (tonnes. 2017)                                                                                7
Red List Index (value, 2019)                                                                                                           0
Skilled labour force (% of labour force, 2010-2019)                                                                                   30
Research and development expenditure (% of GDP, 2014-2018)                                                                            53
Continent                                                                                                                              0
dtype: int64

In [13]:
##############
##Creating dict with the means for each Continent!
#########
africa_mean = df_cols_mean.iloc[0].to_dict()
asia_mean = df_cols_mean.iloc[1].to_dict()
europe_mean = df_cols_mean.iloc[2].to_dict()
north_america_mean = df_cols_mean.iloc[3].to_dict()
oceania_mean = df_cols_mean.iloc[4].to_dict()
south_america_mean = df_cols_mean.iloc[5].to_dict()
##############

In [14]:
#####'Gender Development Index - Value (2019)'#####

### Creating the 'Gender Development Index - Value (2019)' dataset with missing values!
gdiv = df_full[['Gender Development Index - Value (2019)','Continent']]

##Creating the variables for the 'Gender Development Index - Value (2019)' missing values!!!
gdiv_africa = africa_mean['Gender Development Index - Value (2019)']
gdiv_asia = asia_mean['Gender Development Index - Value (2019)']
gdiv_europe = europe_mean['Gender Development Index - Value (2019)']
gdiv_north_america = north_america_mean['Gender Development Index - Value (2019)']
gdiv_oceania = oceania_mean['Gender Development Index - Value (2019)']
gdiv_south_america = south_america_mean['Gender Development Index - Value (2019)']

#filling the 'Gender Development Index - Value (2019)' missing values with the variables!!!
gdiv.loc[gdiv['Continent'] == 'Africa'] = gdiv.loc[gdiv['Continent'] == 'Africa'].fillna(gdiv_africa)
gdiv.loc[gdiv['Continent'] == 'Asia'] = gdiv.loc[gdiv['Continent'] == 'Asia'].fillna(gdiv_asia)
gdiv.loc[gdiv['Continent'] == 'Europe'] = gdiv.loc[gdiv['Continent'] == 'Europe'].fillna(gdiv_europe)
gdiv.loc[gdiv['Continent'] == 'North America'] = gdiv.loc[gdiv['Continent'] == 'North America'].fillna(gdiv_north_america)
gdiv.loc[gdiv['Continent'] == 'Oceania'] = gdiv.loc[gdiv['Continent'] == 'Oceania'].fillna(gdiv_oceania)
gdiv.loc[gdiv['Continent'] == 'South America'] = gdiv.loc[gdiv['Continent'] == 'South America'].fillna(gdiv_south_america)

#renaming the columns
gdiv = gdiv.rename(columns={'Continent':'Continent2'})
gdiv = gdiv.rename(columns={'Gender Development Index - Value (2019)':'GDIV (gender development index value, 2019)'})

#joinning the datasets
df_full = df_full.join(gdiv, on='Country', how='left')

#dropping the extra columns
df_full = df_full.drop(['Gender Development Index - Value (2019)', 'Continent2'], axis=1)

gdiv.isnull().sum()

C:\Users\lisaf\anaconda3\lib\site-packages\pandas\core\indexing.py:1717: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, v)

GDIV (gender development index value, 2019)    0
Continent2                                     0
dtype: int64

In [15]:
###### 'Gender Inequality Index Value (2019)' ######

### Creating the 'Gender Inequality Index Value (2019)' dataset with missing values!
giiv = df_full[['Gender Inequality Index Value (2019)','Continent']]

#Creating the variables for the 'Gender Inequality Index Value (2019)' missing values!!!
giiv_africa = africa_mean['Gender Inequality Index Value (2019)']
giiv_asia = asia_mean['Gender Inequality Index Value (2019)']
giiv_europe = europe_mean['Gender Inequality Index Value (2019)']
giiv_north_america = north_america_mean['Gender Inequality Index Value (2019)']
giiv_oceania = oceania_mean['Gender Inequality Index Value (2019)']
giiv_south_america = south_america_mean['Gender Inequality Index Value (2019)']

#filling the 'Gender Inequality Index Value (2019)' missing values with the variables!!!
giiv.loc[giiv['Continent'] == 'Africa'] = giiv.loc[giiv['Continent'] == 'Africa'].fillna(giiv_africa)
giiv.loc[giiv['Continent'] == 'Asia'] = giiv.loc[giiv['Continent'] == 'Asia'].fillna(giiv_asia)
giiv.loc[giiv['Continent'] == 'Europe'] = giiv.loc[giiv['Continent'] == 'Europe'].fillna(giiv_europe)
giiv.loc[giiv['Continent'] == 'North America'] = giiv.loc[giiv['Continent'] == 'North America'].fillna(giiv_north_america)
giiv.loc[giiv['Continent'] == 'Oceania'] = giiv.loc[giiv['Continent'] == 'Oceania'].fillna(giiv_oceania)
giiv.loc[giiv['Continent'] == 'South America'] = giiv.loc[giiv['Continent'] == 'South America'].fillna(giiv_south_america)

#renaming the columns
giiv = giiv.rename(columns={'Continent':'Continent2'})
giiv = giiv.rename(columns={'Gender Inequality Index Value (2019)':'GIIV (gender inequality index value, 2019)'})

#joinning the datasets
df_full = df_full.join(giiv, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Gender Inequality Index Value (2019)', 'Continent2'], axis=1)

#df_full.head()
giiv.isnull().sum()

GIIV (gender inequality index value, 2019)    0
Continent2                                    0
dtype: int64

In [16]:
###### 'Inequality-adjusted HDI (IHDI) Value 2019' #####

### Creating the 'Inequality-adjusted HDI (IHDI) Value 2019' dataset with missing values!
ihdi = df_full[['Inequality-adjusted HDI (IHDI) Value 2019','Continent']]

#Creating the variables for the'Inequality-adjusted HDI (IHDI) Value 2019' missing values!!!
ihdi_africa = africa_mean['Inequality-adjusted HDI (IHDI) Value 2019']
ihdi_asia = asia_mean['Inequality-adjusted HDI (IHDI) Value 2019']
ihdi_europe = europe_mean['Inequality-adjusted HDI (IHDI) Value 2019']
ihdi_north_america = north_america_mean['Inequality-adjusted HDI (IHDI) Value 2019']
ihdi_oceania = oceania_mean['Inequality-adjusted HDI (IHDI) Value 2019']
ihdi_south_america = south_america_mean['Inequality-adjusted HDI (IHDI) Value 2019']

#filling the'Inequality-adjusted HDI (IHDI) Value 2019' missing values with the variables!!!
ihdi.loc[ihdi['Continent'] == 'Africa'] = ihdi.loc[ihdi['Continent'] == 'Africa'].fillna(ihdi_africa)
ihdi.loc[ihdi['Continent'] == 'Asia'] = ihdi.loc[ihdi['Continent'] == 'Asia'].fillna(ihdi_asia)
ihdi.loc[ihdi['Continent'] == 'Europe'] = ihdi.loc[ihdi['Continent'] == 'Europe'].fillna(ihdi_europe)
ihdi.loc[ihdi['Continent'] == 'North America'] = ihdi.loc[ihdi['Continent'] == 'North America'].fillna(ihdi_north_america)
ihdi.loc[ihdi['Continent'] == 'Oceania'] = ihdi.loc[ihdi['Continent'] == 'Oceania'].fillna(ihdi_oceania)
ihdi.loc[ihdi['Continent'] == 'South America'] = ihdi.loc[ihdi['Continent'] == 'South America'].fillna(ihdi_south_america)

#renaming the columns
ihdi = ihdi.rename(columns={'Continent':'Continent2'})
ihdi = ihdi.rename(columns={'Inequality-adjusted HDI (IHDI) Value 2019':'IHDI (gender inequality index value, 2019)'})

#joinning the datasets
df_full = df_full.join(ihdi, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Inequality-adjusted HDI (IHDI) Value 2019', 'Continent2'], axis=1)

#df_full.head()
ihdi.isnull().sum()

IHDI (gender inequality index value, 2019)    0
Continent2                                    0
dtype: int64

In [17]:
###### 'Inequality in life expectancy (%, 2015-2020)' #####

### Creating the 'Inequality in life expectancy (%, 2015-2020)' dataset with missing values!
ile = df_full[['Inequality in life expectancy (%, 2015-2020)','Continent']]

#Creating the variables for the'Inequality in life expectancy (%, 2015-2020)' missing values!!!
ile_africa = africa_mean['Inequality in life expectancy (%, 2015-2020)']
ile_asia = asia_mean['Inequality in life expectancy (%, 2015-2020)']
ile_europe = europe_mean['Inequality in life expectancy (%, 2015-2020)']
ile_north_america = north_america_mean['Inequality in life expectancy (%, 2015-2020)']
ile_oceania = oceania_mean['Inequality in life expectancy (%, 2015-2020)']
ile_south_america = south_america_mean['Inequality in life expectancy (%, 2015-2020)']

#filling the'Inequality in life expectancy (%, 2015-2020)' missing values with the variables!!!
ile.loc[ile['Continent'] == 'Africa'] = ile.loc[ile['Continent'] == 'Africa'].fillna(ile_africa)
ile.loc[ile['Continent'] == 'Asia'] = ile.loc[ile['Continent'] == 'Asia'].fillna(ile_asia)
ile.loc[ile['Continent'] == 'Europe'] = ile.loc[ile['Continent'] == 'Europe'].fillna(ile_europe)
ile.loc[ile['Continent'] == 'North America'] = ile.loc[ile['Continent'] == 'North America'].fillna(ile_north_america)
ile.loc[ile['Continent'] == 'Oceania'] = ile.loc[ile['Continent'] == 'Oceania'].fillna(ile_oceania)
ile.loc[ile['Continent'] == 'South America'] = ile.loc[ile['Continent'] == 'South America'].fillna(ile_south_america)

#renaming the columns
ile = ile.rename(columns={'Continent':'Continent2'})
ile = ile.rename(columns={'Inequality in life expectancy (%, 2015-2020)':'ILE (inequality in life expectancy, %, 2015-2020)'})

#joinning the datasets
df_full = df_full.join(ile, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Inequality in life expectancy (%, 2015-2020)', 'Continent2'], axis=1)

#df_full.head()
ile.isnull().sum()

ILE (inequality in life expectancy, %, 2015-2020)    0
Continent2                                           0
dtype: int64

In [18]:
###### 'Inequality in education (%, 2019)' #####

### Creating the 'Inequality in education (%, 2019)' dataset with missing values!
ie = df_full[['Inequality in education (%, 2019)','Continent']]

#Creating the variables for the'Inequality in education (%, 2019)' missing values!!!
ie_africa = africa_mean['Inequality in education (%, 2019)']
ie_asia = asia_mean['Inequality in education (%, 2019)']
ie_europe = europe_mean['Inequality in education (%, 2019)']
ie_north_america = north_america_mean['Inequality in education (%, 2019)']
ie_oceania = oceania_mean['Inequality in education (%, 2019)']
ie_south_america = south_america_mean['Inequality in education (%, 2019)']

#filling the'Inequality in education (%, 2019)' missing values with the variables!!!
ie.loc[ie['Continent'] == 'Africa'] = ie.loc[ie['Continent'] == 'Africa'].fillna(ie_africa)
ie.loc[ie['Continent'] == 'Asia'] = ie.loc[ie['Continent'] == 'Asia'].fillna(ie_asia)
ie.loc[ie['Continent'] == 'Europe'] = ie.loc[ie['Continent'] == 'Europe'].fillna(ie_europe)
ie.loc[ie['Continent'] == 'North America'] = ie.loc[ie['Continent'] == 'North America'].fillna(ie_north_america)
ie.loc[ie['Continent'] == 'Oceania'] = ie.loc[ie['Continent'] == 'Oceania'].fillna(ie_oceania)
ie.loc[ie['Continent'] == 'South America'] = ie.loc[ie['Continent'] == 'South America'].fillna(ie_south_america)

#renaming the columns
ie = ie.rename(columns={'Continent':'Continent2'})
ie = ie.rename(columns={'Inequality in education (%, 2019)':'IE (inequality in education, %, 2019)'})

#joinning the datasets
df_full = df_full.join(ie, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Inequality in education (%, 2019)', 'Continent2'], axis=1)

#df_full.head()
ie.isnull().sum()

IE (inequality in education, %, 2019)    0
Continent2                               0
dtype: int64

In [19]:
###### Inequality in income (%, 2019) ######

### Creating the 'Inequality in income (%, 2019)' dataset with missing values!
ii = df_full[['Inequality in income (%, 2019)','Continent']]

#Creating the variables for the 'Inequality in income (%, 2019)' missing values!!!
ii_africa = africa_mean['Inequality in income (%, 2019)']
ii_asia = asia_mean['Inequality in income (%, 2019)']
ii_europe = europe_mean['Inequality in income (%, 2019)']
ii_north_america = north_america_mean['Inequality in income (%, 2019)']
ii_oceania = oceania_mean['Inequality in income (%, 2019)']
ii_south_america = south_america_mean['Inequality in income (%, 2019)']

#filling the 'Inequality in income (%, 2019)' missing values with the variables!!!
ii.loc[ii['Continent'] == 'Africa'] = ii.loc[ii['Continent'] == 'Africa'].fillna(ii_africa)
ii.loc[ii['Continent'] == 'Asia'] = ii.loc[ii['Continent'] == 'Asia'].fillna(ii_asia)
ii.loc[ii['Continent'] == 'Europe'] = ii.loc[ii['Continent'] == 'Europe'].fillna(ii_europe)
ii.loc[ii['Continent'] == 'North America'] = ii.loc[ii['Continent'] == 'North America'].fillna(ii_north_america)
ii.loc[ii['Continent'] == 'Oceania'] = ii.loc[ii['Continent'] == 'Oceania'].fillna(ii_oceania)
ii.loc[ii['Continent'] == 'South America'] = ii.loc[ii['Continent'] == 'South America'].fillna(ii_south_america)

#renaming the columns
ii = ii.rename(columns={'Continent':'Continent2'})
ii = ii.rename(columns={'Inequality in income (%, 2019)':'II (inequality in income, %, 2019)'})

#joinning the datasets
df_full = df_full.join(ii, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Inequality in income (%, 2019)', 'Continent2'], axis=1)

#df_full.head()
ii.isnull().sum()

II (inequality in income, %, 2019)    0
Continent2                            0
dtype: int64

In [20]:
##### Share of seats in parliament (% held by women, 2019) ######

### Creating the 'Share of seats in parliament (% held by women, 2019)' dataset with missing values!
ssp = df_full[['Share of seats in parliament (% held by women, 2019)','Continent']]

#Creating the variables for the 'Share of seats in parliament (% held by women, 2019)' missing values!!!
ssp_africa = africa_mean['Share of seats in parliament (% held by women, 2019)']
ssp_asia = asia_mean['Share of seats in parliament (% held by women, 2019)']
ssp_europe = europe_mean['Share of seats in parliament (% held by women, 2019)']
ssp_north_america = north_america_mean['Share of seats in parliament (% held by women, 2019)']
ssp_oceania = oceania_mean['Share of seats in parliament (% held by women, 2019)']
ssp_south_america = south_america_mean['Share of seats in parliament (% held by women, 2019)']

#filling the 'Share of seats in parliament (% held by women, 2019)' missing values with the variables!!!
ssp.loc[ssp['Continent'] == 'Africa'] = ssp.loc[ssp['Continent'] == 'Africa'].fillna(ssp_africa)
ssp.loc[ssp['Continent'] == 'Asia'] = ssp.loc[ssp['Continent'] == 'Asia'].fillna(ssp_asia)
ssp.loc[ssp['Continent'] == 'Europe'] = ssp.loc[ssp['Continent'] == 'Europe'].fillna(ssp_europe)
ssp.loc[ssp['Continent'] == 'North America'] = ssp.loc[ssp['Continent'] == 'North America'].fillna(ssp_north_america)
ssp.loc[ssp['Continent'] == 'Oceania'] = ssp.loc[ssp['Continent'] == 'Oceania'].fillna(ssp_oceania)
ssp.loc[ssp['Continent'] == 'South America'] = ssp.loc[ssp['Continent'] == 'South America'].fillna(ssp_south_america)

#renaming the columns
ssp = ssp.rename(columns={'Continent':'Continent2'})
ssp = ssp.rename(columns={'Share of seats in parliament (% held by women, 2019)':'SSP (share of seats in parliament, % held by women, 2019)'})

#joinning the datasets
df_full = df_full.join(ssp, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Share of seats in parliament (% held by women, 2019)', 'Continent2'], axis=1)

#df_full.head()
ssp.isnull().sum()

SSP (share of seats in parliament, % held by women, 2019)    0
Continent2                                                   0
dtype: int64

In [21]:
##### Median age (years, 2020) #####

### Creating the 'Median age (years, 2020)' dataset with missing values!
ma = df_full[['Median age (years, 2020)','Continent']]

#Creating the variables for the 'Median age (years, 2020)' missing values!!!
ma_africa = africa_mean['Median age (years, 2020)']
ma_asia = asia_mean['Median age (years, 2020)']
ma_europe = europe_mean['Median age (years, 2020)']
ma_north_america = north_america_mean['Median age (years, 2020)']
ma_oceania = oceania_mean['Median age (years, 2020)']
ma_south_america = south_america_mean['Median age (years, 2020)']

#filling the 'Median age (years, 2020)' missing values with the variables!!!
ma.loc[ma['Continent'] == 'Africa'] = ma.loc[ma['Continent'] == 'Africa'].fillna(ma_africa)
ma.loc[ma['Continent'] == 'Asia'] = ma.loc[ma['Continent'] == 'Asia'].fillna(ma_asia)
ma.loc[ma['Continent'] == 'Europe'] = ma.loc[ma['Continent'] == 'Europe'].fillna(ma_europe)
ma.loc[ma['Continent'] == 'North America'] = ma.loc[ma['Continent'] == 'North America'].fillna(ma_north_america)
ma.loc[ma['Continent'] == 'Oceania'] = ma.loc[ma['Continent'] == 'Oceania'].fillna(ma_oceania)
ma.loc[ma['Continent'] == 'South America'] = ma.loc[ma['Continent'] == 'South America'].fillna(ma_south_america)

#renaming the columns
ma = ma.rename(columns={'Continent':'Continent2'})
ma = ma.rename(columns={'Median age (years, 2020)':'MA (median age, years, 2020)'})

#joinning the datasets
df_full = df_full.join(ma, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Median age (years, 2020)', 'Continent2'], axis=1)

#df_full.head()
ma.isnull().sum()

MA (median age, years, 2020)    0
Continent2                      0
dtype: int64

In [22]:
##### Current health expenditure (% of GDP) #####

### Creating the 'Current health expenditure (% of GDP)' dataset with missing values!
che = df_full[['Current health expenditure (% of GDP)','Continent']]

#Creating the variables for the 'Current health expenditure (% of GDP)' missing values!!!
che_africa = africa_mean['Current health expenditure (% of GDP)']
che_asia = asia_mean['Current health expenditure (% of GDP)']
che_europe = europe_mean['Current health expenditure (% of GDP)']
che_north_america = north_america_mean['Current health expenditure (% of GDP)']
che_oceania = oceania_mean['Current health expenditure (% of GDP)']
che_south_america = south_america_mean['Current health expenditure (% of GDP)']

#filling the 'Current health expenditure (% of GDP)' missing values with the variables!!!
che.loc[che['Continent'] == 'Africa'] = che.loc[che['Continent'] == 'Africa'].fillna(che_africa)
che.loc[che['Continent'] == 'Asia'] = che.loc[che['Continent'] == 'Asia'].fillna(che_asia)
che.loc[che['Continent'] == 'Europe'] = che.loc[che['Continent'] == 'Europe'].fillna(che_europe)
che.loc[che['Continent'] == 'North America'] = che.loc[che['Continent'] == 'North America'].fillna(che_north_america)
che.loc[che['Continent'] == 'Oceania'] = che.loc[che['Continent'] == 'Oceania'].fillna(che_oceania)
che.loc[che['Continent'] == 'South America'] = che.loc[che['Continent'] == 'South America'].fillna(che_south_america)

#renaming the columns
che = che.rename(columns={'Continent':'Continent2'})
che = che.rename(columns={'Current health expenditure (% of GDP)':'CHE (current health expenditure, % of GDP)'})

#joinning the datasets
df_full = df_full.join(che, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Current health expenditure (% of GDP)', 'Continent2'], axis=1)

#df_full.head()
che.isnull().sum()

CHE (current health expenditure, % of GDP)    0
Continent2                                    0
dtype: int64

In [23]:
##### Government expenditure on education  (% of GDP, 2013-2018) #####

### Creating the 'Government expenditure on education  (% of GDP, 2013-2018)' dataset with missing values!
gee = df_full[['Government expenditure on education  (% of GDP, 2013-2018)','Continent']]

#Creating the variables for the 'Government expenditure on education  (% of GDP, 2013-2018)' missing values!!!
gee_africa = africa_mean['Government expenditure on education  (% of GDP, 2013-2018)']
gee_asia = asia_mean['Government expenditure on education  (% of GDP, 2013-2018)']
gee_europe = europe_mean['Government expenditure on education  (% of GDP, 2013-2018)']
gee_north_america = north_america_mean['Government expenditure on education  (% of GDP, 2013-2018)']
gee_oceania = oceania_mean['Government expenditure on education  (% of GDP, 2013-2018)']
gee_south_america = south_america_mean['Government expenditure on education  (% of GDP, 2013-2018)']

#filling the 'Government expenditure on education  (% of GDP, 2013-2018)' missing values with the variables!!!
gee.loc[gee['Continent'] == 'Africa'] = gee.loc[gee['Continent'] == 'Africa'].fillna(gee_africa)
gee.loc[gee['Continent'] == 'Asia'] = gee.loc[gee['Continent'] == 'Asia'].fillna(gee_asia)
gee.loc[gee['Continent'] == 'Europe'] = gee.loc[gee['Continent'] == 'Europe'].fillna(gee_europe)
gee.loc[gee['Continent'] == 'North America'] = gee.loc[gee['Continent'] == 'North America'].fillna(gee_north_america)
gee.loc[gee['Continent'] == 'Oceania'] = gee.loc[gee['Continent'] == 'Oceania'].fillna(gee_oceania)
gee.loc[gee['Continent'] == 'South America'] = gee.loc[gee['Continent'] == 'South America'].fillna(gee_south_america)

#renaming the columns
gee = gee.rename(columns={'Continent':'Continent2'})
gee = gee.rename(columns={'Government expenditure on education  (% of GDP, 2013-2018)':'GEE (government expenditure on education, % of GDP, 2013-2018)'})

#joinning the datasets
df_full = df_full.join(gee, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Government expenditure on education  (% of GDP, 2013-2018)', 'Continent2'], axis=1)

#df_full.head()
gee.isnull().sum()

GEE (government expenditure on education, % of GDP, 2013-2018)    0
Continent2                                                        0
dtype: int64

In [24]:
##### Physicians per 10000 people (2010-2018) #####

### Creating the 'Physicians per 10000 people (2010-2018)' dataset with missing values!
ppp = df_full[['Physicians per 10000 people (2010-2018)','Continent']]

#Creating the variables for the 'Physicians per 10000 people (2010-2018)' missing values!!!
ppp_africa = africa_mean['Physicians per 10000 people (2010-2018)']
ppp_asia = asia_mean['Physicians per 10000 people (2010-2018)']
ppp_europe = europe_mean['Physicians per 10000 people (2010-2018)']
ppp_north_america = north_america_mean['Physicians per 10000 people (2010-2018)']
ppp_oceania = oceania_mean['Physicians per 10000 people (2010-2018)']
ppp_south_america = south_america_mean['Physicians per 10000 people (2010-2018)']

#filling the 'Physicians per 10000 people (2010-2018)' missing values with the variables!!!
ppp.loc[ppp['Continent'] == 'Africa'] = ppp.loc[ppp['Continent'] == 'Africa'].fillna(ppp_africa)
ppp.loc[ppp['Continent'] == 'Asia'] = ppp.loc[ppp['Continent'] == 'Asia'].fillna(ppp_asia)
ppp.loc[ppp['Continent'] == 'Europe'] = ppp.loc[ppp['Continent'] == 'Europe'].fillna(ppp_europe)
ppp.loc[ppp['Continent'] == 'North America'] = ppp.loc[ppp['Continent'] == 'North America'].fillna(ppp_north_america)
ppp.loc[ppp['Continent'] == 'Oceania'] = ppp.loc[ppp['Continent'] == 'Oceania'].fillna(ppp_oceania)
ppp.loc[ppp['Continent'] == 'South America'] = ppp.loc[ppp['Continent'] == 'South America'].fillna(ppp_south_america)

#renaming the columns
ppp = ppp.rename(columns={'Continent':'Continent2'})
ppp = ppp.rename(columns={'Physicians per 10000 people (2010-2018)':'PPP (physicians per 10000 people, 2010-2018)'})

#joinning the datasets
df_full = df_full.join(ppp, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Physicians per 10000 people (2010-2018)', 'Continent2'], axis=1)

#df_full.head()
ppp.isnull().sum()

PPP (physicians per 10000 people, 2010-2018)    0
Continent2                                      0
dtype: int64

In [25]:
##### Hospital beds (per 10,000 people, 2010-2019) #####

### Creating the 'Hospital beds (per 10,000 people, 2010-2019)' dataset with missing values!
hb = df_full[['Hospital beds (per 10,000 people, 2010-2019)','Continent']]

#Creating the variables for the 'Hospital beds (per 10,000 people, 2010-2019)' missing values!!!
hb_africa = africa_mean['Hospital beds (per 10,000 people, 2010-2019)']
hb_asia = asia_mean['Hospital beds (per 10,000 people, 2010-2019)']
hb_europe = europe_mean['Hospital beds (per 10,000 people, 2010-2019)']
hb_north_america = north_america_mean['Hospital beds (per 10,000 people, 2010-2019)']
hb_oceania = oceania_mean['Hospital beds (per 10,000 people, 2010-2019)']
hb_south_america = south_america_mean['Hospital beds (per 10,000 people, 2010-2019)']

#filling the 'Hospital beds (per 10,000 people, 2010-2019)' missing values with the variables!!!
hb.loc[hb['Continent'] == 'Africa'] = hb.loc[hb['Continent'] == 'Africa'].fillna(hb_africa)
hb.loc[hb['Continent'] == 'Asia'] = hb.loc[hb['Continent'] == 'Asia'].fillna(hb_asia)
hb.loc[hb['Continent'] == 'Europe'] = hb.loc[hb['Continent'] == 'Europe'].fillna(hb_europe)
hb.loc[hb['Continent'] == 'North America'] = hb.loc[hb['Continent'] == 'North America'].fillna(hb_north_america)
hb.loc[hb['Continent'] == 'Oceania'] = hb.loc[hb['Continent'] == 'Oceania'].fillna(hb_oceania)
hb.loc[hb['Continent'] == 'South America'] = hb.loc[hb['Continent'] == 'South America'].fillna(hb_south_america)

#renaming the columns
hb = hb.rename(columns={'Continent':'Continent2'})
hb = hb.rename(columns={'Hospital beds (per 10,000 people, 2010-2019)':'HB (hospital beds per 10000 people, 2010-2019)'})

#joinning the datasets
df_full = df_full.join(hb, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Hospital beds (per 10,000 people, 2010-2019)', 'Continent2'], axis=1)

#df_full.head()
hb.isnull().sum()

HB (hospital beds per 10000 people, 2010-2019)    0
Continent2                                        0
dtype: int64

In [26]:
##### Vulnerable employment (% of total employment, 2019)\n #####

### Creating the 'Vulnerable employment (% of total employment, 2019)\n' dataset with missing values!
ve = df_full[['Vulnerable employment (% of total employment, 2019)\n','Continent']]

#Creating the variables for the 'Vulnerable employment (% of total employment, 2019)\n' missing values!!!
ve_africa = africa_mean['Vulnerable employment (% of total employment, 2019)\n']
ve_asia = asia_mean['Vulnerable employment (% of total employment, 2019)\n']
ve_europe = europe_mean['Vulnerable employment (% of total employment, 2019)\n']
ve_north_america = north_america_mean['Vulnerable employment (% of total employment, 2019)\n']
ve_oceania = oceania_mean['Vulnerable employment (% of total employment, 2019)\n']
ve_south_america = south_america_mean['Vulnerable employment (% of total employment, 2019)\n']

#filling the 'Vulnerable employment (% of total employment, 2019)\n' missing values with the variables!!!
ve.loc[ve['Continent'] == 'Africa'] = ve.loc[ve['Continent'] == 'Africa'].fillna(ve_africa)
ve.loc[ve['Continent'] == 'Asia'] = ve.loc[ve['Continent'] == 'Asia'].fillna(ve_asia)
ve.loc[ve['Continent'] == 'Europe'] = ve.loc[ve['Continent'] == 'Europe'].fillna(ve_europe)
ve.loc[ve['Continent'] == 'North America'] = ve.loc[ve['Continent'] == 'North America'].fillna(ve_north_america)
ve.loc[ve['Continent'] == 'Oceania'] = ve.loc[ve['Continent'] == 'Oceania'].fillna(ve_oceania)
ve.loc[ve['Continent'] == 'South America'] = ve.loc[ve['Continent'] == 'South America'].fillna(ve_south_america)

#renaming the columns
ve = ve.rename(columns={'Continent':'Continent2'})
ve = ve.rename(columns={'Vulnerable employment (% of total employment, 2019)\n':'VE (vulnerable employment, % of total employment, 2019)'})

#joinning the datasets
df_full = df_full.join(ve, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Vulnerable employment (% of total employment, 2019)\n', 'Continent2'], axis=1)

#df_full.head()
ve.isnull().sum()

VE (vulnerable employment, % of total employment, 2019)    0
Continent2                                                 0
dtype: int64

In [27]:
##### Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017) #####

### Creating the 'Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)' dataset with missing values!
wafi = df_full[['Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)','Continent']]

#Creating the variables for the 'Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)' missing values!!!
wafi_africa = africa_mean['Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)']
wafi_asia = asia_mean['Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)']
wafi_europe = europe_mean['Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)']
wafi_north_america = north_america_mean['Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)']
wafi_oceania = oceania_mean['Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)']
wafi_south_america = south_america_mean['Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)']

#filling the 'Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)' missing values with the variables!!!
wafi.loc[wafi['Continent'] == 'Africa'] = wafi.loc[wafi['Continent'] == 'Africa'].fillna(wafi_africa)
wafi.loc[wafi['Continent'] == 'Asia'] = wafi.loc[wafi['Continent'] == 'Asia'].fillna(wafi_asia)
wafi.loc[wafi['Continent'] == 'Europe'] = wafi.loc[wafi['Continent'] == 'Europe'].fillna(wafi_europe)
wafi.loc[wafi['Continent'] == 'North America'] = wafi.loc[wafi['Continent'] == 'North America'].fillna(wafi_north_america)
wafi.loc[wafi['Continent'] == 'Oceania'] = wafi.loc[wafi['Continent'] == 'Oceania'].fillna(wafi_oceania)
wafi.loc[wafi['Continent'] == 'South America'] = wafi.loc[wafi['Continent'] == 'South America'].fillna(wafi_south_america)

#renaming the columns
wafi = wafi.rename(columns={'Continent':'Continent2'})
wafi = wafi.rename(columns={'Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)':'WAFI (Women with account at financial institution or with mobile money-service provider, % of female population ages 15 and older, 2017)'})

#joinning the datasets
df_full = df_full.join(wafi, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Women with account at financial institution or with mobile money-service provider (% of female population ages 15 and older, 2017)', 'Continent2'], axis=1)

#df_full.head()
wafi.isnull().sum()

WAFI (Women with account at financial institution or with mobile money-service provider, % of female population ages 15 and older, 2017)    0
Continent2                                                                                                                                  0
dtype: int64

In [28]:
##### Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP) #####

### Creating the 'Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)' dataset with missing values!
cde = df_full[['Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)','Continent']]

#Creating the variables for the 'Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)' missing values!!!
cde_africa = africa_mean['Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)']
cde_asia = asia_mean['Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)']
cde_europe = europe_mean['Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)']
cde_north_america = north_america_mean['Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)']
cde_oceania = oceania_mean['Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)']
cde_south_america = south_america_mean['Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)']

#filling the 'Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)' missing values with the variables!!!
cde.loc[cde['Continent'] == 'Africa'] = cde.loc[cde['Continent'] == 'Africa'].fillna(cde_africa)
cde.loc[cde['Continent'] == 'Asia'] = cde.loc[cde['Continent'] == 'Asia'].fillna(cde_asia)
cde.loc[cde['Continent'] == 'Europe'] = cde.loc[cde['Continent'] == 'Europe'].fillna(cde_europe)
cde.loc[cde['Continent'] == 'North America'] = cde.loc[cde['Continent'] == 'North America'].fillna(cde_north_america)
cde.loc[cde['Continent'] == 'Oceania'] = cde.loc[cde['Continent'] == 'Oceania'].fillna(cde_oceania)
cde.loc[cde['Continent'] == 'South America'] = cde.loc[cde['Continent'] == 'South America'].fillna(cde_south_america)

#renaming the columns
cde = cde.rename(columns={'Continent':'Continent2'})
cde = cde.rename(columns={'Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)':'CDE (Carbon dioxide emissions per unit of GDP, kg per 2010 US$ of GDP)'})

#joinning the datasets
df_full = df_full.join(cde, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Carbon dioxide emissions: Per unit of GDP (kg per 2010 US$ of GDP)', 'Continent2'], axis=1)

#df_full.head()
cde.isnull().sum()

CDE (Carbon dioxide emissions per unit of GDP, kg per 2010 US$ of GDP)    0
Continent2                                                                0
dtype: int64

In [29]:
##### Forest area (% of total land area, 2016) #####

### Creating the 'Forest area (% of total land area, 2016)' dataset with missing values!
fa = df_full[['Forest area (% of total land area, 2016)','Continent']]

#Creating the variables for the 'Forest area (% of total land area, 2016)' missing values!!!
fa_africa = africa_mean['Forest area (% of total land area, 2016)']
fa_asia = asia_mean['Forest area (% of total land area, 2016)']
fa_europe = europe_mean['Forest area (% of total land area, 2016)']
fa_north_america = north_america_mean['Forest area (% of total land area, 2016)']
fa_oceania = oceania_mean['Forest area (% of total land area, 2016)']
fa_south_america = south_america_mean['Forest area (% of total land area, 2016)']

#filling the 'Forest area (% of total land area, 2016)' missing values with the variables!!!
fa.loc[fa['Continent'] == 'Africa'] = fa.loc[fa['Continent'] == 'Africa'].fillna(fa_africa)
fa.loc[fa['Continent'] == 'Asia'] = fa.loc[fa['Continent'] == 'Asia'].fillna(fa_asia)
fa.loc[fa['Continent'] == 'Europe'] = fa.loc[fa['Continent'] == 'Europe'].fillna(fa_europe)
fa.loc[fa['Continent'] == 'North America'] = fa.loc[fa['Continent'] == 'North America'].fillna(fa_north_america)
fa.loc[fa['Continent'] == 'Oceania'] = fa.loc[fa['Continent'] == 'Oceania'].fillna(fa_oceania)
fa.loc[fa['Continent'] == 'South America'] = fa.loc[fa['Continent'] == 'South America'].fillna(fa_south_america)

#renaming the columns
fa = fa.rename(columns={'Continent':'Continent2'})
fa = fa.rename(columns={'Forest area (% of total land area, 2016)':'FA (forest area, % of total land area, 2016)'})

#joinning the datasets
df_full = df_full.join(fa, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Forest area (% of total land area, 2016)', 'Continent2'], axis=1)

#df_full.head()
fa.isnull().sum()

FA (forest area, % of total land area, 2016)    0
Continent2                                      0
dtype: int64

In [30]:
##### Forest area - Change 1990/2016 (%) #####

### Creating the 'Forest area - Change 1990/2016 (%)' dataset with missing values!
fac = df_full[['Forest area - Change 1990/2016 (%)','Continent']]

#Creating the variables for the 'Forest area - Change 1990/2016 (%)' missing values!!!
fac_africa = africa_mean['Forest area - Change 1990/2016 (%)']
fac_asia = asia_mean['Forest area - Change 1990/2016 (%)']
fac_europe = europe_mean['Forest area - Change 1990/2016 (%)']
fac_north_america = north_america_mean['Forest area - Change 1990/2016 (%)']
fac_oceania = oceania_mean['Forest area - Change 1990/2016 (%)']
fac_south_america = south_america_mean['Forest area - Change 1990/2016 (%)']

#filling the 'Forest area - Change 1990/2016 (%)' missing values with the variables!!!
fac.loc[fac['Continent'] == 'Africa'] = fac.loc[fac['Continent'] == 'Africa'].fillna(fac_africa)
fac.loc[fac['Continent'] == 'Asia'] = fac.loc[fac['Continent'] == 'Asia'].fillna(fac_asia)
fac.loc[fac['Continent'] == 'Europe'] = fac.loc[fac['Continent'] == 'Europe'].fillna(fac_europe)
fac.loc[fac['Continent'] == 'North America'] = fac.loc[fac['Continent'] == 'North America'].fillna(fac_north_america)
fac.loc[fac['Continent'] == 'Oceania'] = fac.loc[fac['Continent'] == 'Oceania'].fillna(fac_oceania)
fac.loc[fac['Continent'] == 'South America'] = fac.loc[fac['Continent'] == 'South America'].fillna(fac_south_america)

#renaming the columns
fac = fac.rename(columns={'Continent':'Continent2'})
fac = fac.rename(columns={'Forest area - Change 1990/2016 (%)':'FAC (forest area change, %, 1990/2016)'})

#joinning the datasets
df_full = df_full.join(fac, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Forest area - Change 1990/2016 (%)', 'Continent2'], axis=1)

#df_full.head()
fac.isnull().sum()

FAC (forest area change, %, 1990/2016)    0
Continent2                                0
dtype: int64

In [31]:
##### Domestic material consumption per capita (tonnes. 2017) #####

### Creating the 'Domestic material consumption per capita (tonnes. 2017)' dataset with missing values!
dmc = df_full[['Domestic material consumption per capita (tonnes. 2017)','Continent']]

#Creating the variables for the 'Domestic material consumption per capita (tonnes. 2017)' missing values!!!
dmc_africa = africa_mean['Domestic material consumption per capita (tonnes. 2017)']
dmc_asia = asia_mean['Domestic material consumption per capita (tonnes. 2017)']
dmc_europe = europe_mean['Domestic material consumption per capita (tonnes. 2017)']
dmc_north_america = north_america_mean['Domestic material consumption per capita (tonnes. 2017)']
dmc_oceania = oceania_mean['Domestic material consumption per capita (tonnes. 2017)']
dmc_south_america = south_america_mean['Domestic material consumption per capita (tonnes. 2017)']

#filling the 'Domestic material consumption per capita (tonnes. 2017)' missing values with the variables!!!
dmc.loc[dmc['Continent'] == 'Africa'] = dmc.loc[dmc['Continent'] == 'Africa'].fillna(dmc_africa)
dmc.loc[dmc['Continent'] == 'Asia'] = dmc.loc[dmc['Continent'] == 'Asia'].fillna(dmc_asia)
dmc.loc[dmc['Continent'] == 'Europe'] = dmc.loc[dmc['Continent'] == 'Europe'].fillna(dmc_europe)
dmc.loc[dmc['Continent'] == 'North America'] = dmc.loc[dmc['Continent'] == 'North America'].fillna(dmc_north_america)
dmc.loc[dmc['Continent'] == 'Oceania'] = dmc.loc[dmc['Continent'] == 'Oceania'].fillna(dmc_oceania)
dmc.loc[dmc['Continent'] == 'South America'] = dmc.loc[dmc['Continent'] == 'South America'].fillna(dmc_south_america)

#renaming the columns
dmc = dmc.rename(columns={'Continent':'Continent2'})
dmc = dmc.rename(columns={'Domestic material consumption per capita (tonnes. 2017)':'DMC (domestic material consumption per capita, tonnes, 2017)'})

#joinning the datasets
df_full = df_full.join(dmc, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Domestic material consumption per capita (tonnes. 2017)', 'Continent2'], axis=1)

#df_full.head()
dmc.isnull().sum()

DMC (domestic material consumption per capita, tonnes, 2017)    0
Continent2                                                      0
dtype: int64

In [32]:
##### Skilled labour force (% of labour force, 2010-2019) #####

### Creating the 'Skilled labour force (% of labour force, 2010-2019)' dataset with missing values!
slf = df_full[['Skilled labour force (% of labour force, 2010-2019)','Continent']]

#Creating the variables for the 'Skilled labour force (% of labour force, 2010-2019)' missing values!!!
slf_africa = africa_mean['Skilled labour force (% of labour force, 2010-2019)']
slf_asia = asia_mean['Skilled labour force (% of labour force, 2010-2019)']
slf_europe = europe_mean['Skilled labour force (% of labour force, 2010-2019)']
slf_north_america = north_america_mean['Skilled labour force (% of labour force, 2010-2019)']
slf_oceania = oceania_mean['Skilled labour force (% of labour force, 2010-2019)']
slf_south_america = south_america_mean['Skilled labour force (% of labour force, 2010-2019)']

#filling the 'Skilled labour force (% of labour force, 2010-2019)' missing values with the variables!!!
slf.loc[slf['Continent'] == 'Africa'] = slf.loc[slf['Continent'] == 'Africa'].fillna(slf_africa)
slf.loc[slf['Continent'] == 'Asia'] = slf.loc[slf['Continent'] == 'Asia'].fillna(slf_asia)
slf.loc[slf['Continent'] == 'Europe'] = slf.loc[slf['Continent'] == 'Europe'].fillna(slf_europe)
slf.loc[slf['Continent'] == 'North America'] = slf.loc[slf['Continent'] == 'North America'].fillna(slf_north_america)
slf.loc[slf['Continent'] == 'Oceania'] = slf.loc[slf['Continent'] == 'Oceania'].fillna(slf_oceania)
slf.loc[slf['Continent'] == 'South America'] = slf.loc[slf['Continent'] == 'South America'].fillna(slf_south_america)

#renaming the columns
slf = slf.rename(columns={'Continent':'Continent2'})
slf = slf.rename(columns={'Skilled labour force (% of labour force, 2010-2019)':'SLF (skilled labour force, % of labour force, 2010-2019)'})

#joinning the datasets
df_full = df_full.join(slf, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Skilled labour force (% of labour force, 2010-2019)', 'Continent2'], axis=1)

#df_full.head()
slf.isnull().sum()

SLF (skilled labour force, % of labour force, 2010-2019)    0
Continent2                                                  0
dtype: int64

In [33]:
##### Research and development expenditure (% of GDP, 2014-2018) #####

### Creating the 'Research and development expenditure (% of GDP, 2014-2018)' dataset with missing values!
rde = df_full[['Research and development expenditure (% of GDP, 2014-2018)','Continent']]

#Creating the variables for the 'Research and development expenditure (% of GDP, 2014-2018)' missing values!!!
rde_africa = africa_mean['Research and development expenditure (% of GDP, 2014-2018)']
rde_asia = asia_mean['Research and development expenditure (% of GDP, 2014-2018)']
rde_europe = europe_mean['Research and development expenditure (% of GDP, 2014-2018)']
rde_north_america = north_america_mean['Research and development expenditure (% of GDP, 2014-2018)']
rde_oceania = oceania_mean['Research and development expenditure (% of GDP, 2014-2018)']
rde_south_america = south_america_mean['Research and development expenditure (% of GDP, 2014-2018)']

#filling the 'Research and development expenditure (% of GDP, 2014-2018)' missing values with the variables!!!
rde.loc[rde['Continent'] == 'Africa'] = rde.loc[rde['Continent'] == 'Africa'].fillna(rde_africa)
rde.loc[rde['Continent'] == 'Asia'] = rde.loc[rde['Continent'] == 'Asia'].fillna(rde_asia)
rde.loc[rde['Continent'] == 'Europe'] = rde.loc[rde['Continent'] == 'Europe'].fillna(rde_europe)
rde.loc[rde['Continent'] == 'North America'] = rde.loc[rde['Continent'] == 'North America'].fillna(rde_north_america)
rde.loc[rde['Continent'] == 'Oceania'] = rde.loc[rde['Continent'] == 'Oceania'].fillna(rde_oceania)
rde.loc[rde['Continent'] == 'South America'] = rde.loc[rde['Continent'] == 'South America'].fillna(rde_south_america)

#renaming the columns
rde = rde.rename(columns={'Continent':'Continent2'})
rde = rde.rename(columns={'Research and development expenditure (% of GDP, 2014-2018)':'RDE (research and development expenditure, % of GDP, 2014-2018)'})

#joinning the datasets
df_full = df_full.join(rde, on='Country', how='left')
#dropping the extra columns
df_full = df_full.drop(['Research and development expenditure (% of GDP, 2014-2018)', 'Continent2'], axis=1)

#df_full.head()
rde.isnull().sum()

RDE (research and development expenditure, % of GDP, 2014-2018)    0
Continent2                                                         0
dtype: int64

In [34]:
##### Renaming the first columns to match the others!!! #####

df_full = df_full.rename(columns={'Ranking_HDI_2019':'RHDI (ranking human development index, 2019)'})
df_full = df_full.rename(columns={'Human Development Index (HDI) Value (2019)':'HDI (human development index value, 2019)'})
df_full = df_full.rename(columns={'Life expectancy at birth (years, 2019)':'LE (life expectancy at birth, years, 2019)'})
df_full = df_full.rename(columns={'Expected years of schooling (years, 2019)':'EYS (expected years of schooling, years, 2019)'})
df_full = df_full.rename(columns={'Mean years of schooling (years, 2019)':'MYS (mean years of schooling, years, 2019)'})
df_full = df_full.rename(columns={'Gross national income (GNI) per capita 2019 (2017 PPP $)':'GNI (gross national income per capita 2019 (2017 PPP $)'})
df_full = df_full.rename(columns={'Total Population (millions, 2019)':'TP (total population, millions, 2019)'})
df_full = df_full.rename(columns={'Total Urban Population (%, 2019)':'TUP (total urban population, %, 2019)'})
df_full = df_full.rename(columns={'Rural population with access to electricity (%, 2018)':'RPAE (rural population with access to electricity, %, 2018)'})
df_full = df_full.rename(columns={'Carbon dioxide emissions: Production emissions per capita (tonnes, 2018)':'CDEP (carbon dioxide emissions production per capita, tonnes, 2018)'})
df_full = df_full.rename(columns={'Red List Index (value, 2019)':'RLI (red list index value, 2019)'})

In [35]:
##### Saving the Data Frame as a csv file!!!#####
pd.DataFrame(df_full).to_csv("df_full.csv", index=False)

In [36]:
df_full.head()

,"RHDI (ranking human development index, 2019)","HDI (human development index value, 2019)","LE (life expectancy at birth, years, 2019)","EYS (expected years of schooling, years, 2019)","MYS (mean years of schooling, years, 2019)",GNI (gross national income per capita 2019 (2017 PPP $),"TP (total population, millions, 2019)","TUP (total urban population, %, 2019)","RPAE (rural population with access to electricity, %, 2018)","CDEP (carbon dioxide emissions production per capita, tonnes, 2018)",...,"PPP (physicians per 10000 people, 2010-2018)","HB (hospital beds per 10000 people, 2010-2019)","VE (vulnerable employment, % of total employment, 2019)","WAFI (Women with account at financial institution or with mobile money-service provider, % of female population ages 15 and older, 2017)","CDE (Carbon dioxide emissions per unit of GDP, kg per 2010 US$ of GDP)","FA (forest area, % of total land area, 2016)","FAC (forest area change, %, 1990/2016)","DMC (domestic material consumption per capita, tonnes, 2017)","SLF (skilled labour force, % of labour force, 2010-2019)","RDE (research and development expenditure, % of GDP, 2014-2018)"
Country,,,,,,,,,,,,,,,,,,,,,
Norway,1,0.957,82.40,18.06615,12.897750,66494.25217,5.378859,82.6,100.0,8.303974,...,29.164000,35.300000,4.906,100.000000,0.10907,33.177860,-0.115284,21.821970,84.2811,2.06985
Ireland,2,0.955,82.31,18.70529,12.666331,68370.58737,4.882498,63.4,100.0,8.079187,...,33.125000,29.700000,10.610,95.307037,0.11213,11.027730,63.376347,13.475270,85.0470,1.14647
Switzerland,2,0.955,83.78,16.32844,13.380812,69393.52076,8.591361,73.8,100.0,4.325016,...,42.957000,46.300000,8.941,98.856651,0.07975,31.830150,9.314837,13.718680,87.3141,3.37286
"Hong Kong, China (SAR)",4,0.949,84.86,16.92947,12.279960,62984.76553,7.436157,100.0,100.0,5.852683,...,18.941457,30.195556,5.717,94.702423,0.10847,22.253228,8.089886,14.219249,76.9800,0.86096
Iceland,4,0.949,82.99,19.08309,12.772787,54682.38057,0.339037,93.9,100.0,10.782476,...,40.778000,28.300000,8.108,84.166024,0.13471,0.503740,213.664589,14.881150,76.1659,2.02994

In [37]:
df_full.isnull().sum()

RHDI (ranking human development index, 2019)                                                                                                0
HDI (human development index value, 2019)                                                                                                   0
LE (life expectancy at birth, years, 2019)                                                                                                  0
EYS (expected years of schooling, years, 2019)                                                                                              0
MYS (mean years of schooling, years, 2019)                                                                                                  0
GNI (gross national income per capita 2019 (2017 PPP $)                                                                                     0
TP (total population, millions, 2019)                                                                                                       0
TUP (total urban population, %, 2019)                                                                                                       0
RPAE (rural population with access to electricity, %, 2018)                                                                                 0
CDEP (carbon dioxide emissions production per capita, tonnes, 2018)                                                                         0
RLI (red list index value, 2019)                                                                                                            0
Continent                                                                                                                                   0
GDIV (gender development index value, 2019)                                                                                                 0
GIIV (gender inequality index value, 2019)                                                                                                  0
IHDI (gender inequality index value, 2019)                                                                                                  0
ILE (inequality in life expectancy, %, 2015-2020)                                                                                           0
IE (inequality in education, %, 2019)                                                                                                       0
II (inequality in income, %, 2019)                                                                                                          0
SSP (share of seats in parliament, % held by women, 2019)                                                                                   0
MA (median age, years, 2020)                                                                                                                0
CHE (current health expenditure, % of GDP)                                                                                                  0
GEE (government expenditure on education, % of GDP, 2013-2018)                                                                              0
PPP (physicians per 10000 people, 2010-2018)                                                                                                0
HB (hospital beds per 10000 people, 2010-2019)                                                                                              0
VE (vulnerable employment, % of total employment, 2019)                                                                                     0
WAFI (Women with account at financial institution or with mobile money-service provider, % of female population ages 15 and older, 2017)    0
CDE (Carbon dioxide emissions per unit of GDP, kg per 2010 US$ of GDP)                                                                      0
FA (forest area, % of total land area, 2016)                                                                                                0
FAC (forest area change, %, 1990/2016)                                                                                                      0
DMC (domestic material consumption per capita, tonnes, 2017)                                                                                0
SLF (skilled labour force, % of labour force, 2010-2019)                                                                                    0
RDE (research and development expenditure, % of GDP, 2014-2018)                                                                             0
dtype: int64